### ISSUE TITLE
Feature: opposite transformation

### ISSUE THREAD

**Issue by ammsalme** [NatLibFi/melinda-muuntaja#64]
For suitable profiles, after saving the transformation result, offer possibility for "opposite" transformation.

This creates a new transformation case, where
previous resulting record is source 
previous source record is target
profile is profile configured as "opposite" for previous profile

**Comment by ammsalme** [comment]
Use case:
- User creates an electronic audiobook from printed book using profile printedToEAudio
- User saves new EAudio record
- User chooses to do opposite transformation so the tool switches newly created EAudio record to source and old printed record to target
- Tool transforms target recording according to rules in profile "EAudioToPrint" which has been marked as (possible) opposite to original printedToEAudio profile

**Comment by natlibfi-arlehiko** [comment]
Already supports e-to-print & print-to-e.
